server:
  port: 8082

spring:
  application:
    name: payment-service

  datasource:
    url: jdbc:h2:mem:order_db
    driver-class-name: org.h2.Driver
    username: sa
    password: ""

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  rabbitmq:
    host: '${RABBIT_HOST:localhost}'
    port: '${RABBIT_PORT:5672}'
    username: '${RABBIT_USERNAME:guest}'
    password: '${RABBIT_PASSWORD:guest}'

resilience4j:
  circuitbreaker:
    instances:
      paymentControllerCircuitBreaker:
        registerHealthIndicator: true
        slidingWindowSize: 50
        failureRateThreshold: 50
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 10
        minimumNumberOfCalls: 20
        ignoreExceptions:
          - com.iproddy.common.exception.NotFoundException

rate-limiter:
  sliding-window:
    per-second: 10
    per-minute: 100
    per-hour: 1000

rabbitmq:
  queue:
    payment-create-request_queue: 'q.order_service.payment_create_events'
    payment-response_queue: 'q.payment_service.payment_events'


