server:
  port: 8081

spring:
  application:
    name: order-service

  datasource:
    url: jdbc:h2:mem:order_db
    driver-class-name: org.h2.Driver
    username: sa
    password: ""

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  cloud:
    openfeign:
      client:
        config:
          payment-client:
            url: http://localhost:8082
            logger-level: full

resilience4j:
  retry:
    instances:
      paymentClientRetry:
        maxAttempts: 3
        waitDuration: 1000ms
        retryExceptions:
          - feign.FeignException
        ignoreExceptions:
          - java.lang.RuntimeException

  circuitbreaker:
    instances:
      orderControllerCircuitBreaker:
        registerHealthIndicator: true
        slidingWindowSize: 50
        failureRateThreshold: 50
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 10
        minimumNumberOfCalls: 20
        ignoreExceptions:
          - com.iproddy.common.exception.NotFoundException
      paymentClientCircuitBreaker:
        registerHealthIndicator: true
        slidingWindowSize: 50
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 5
        minimumNumberOfCalls: 10
        recordExceptions:
          - feign.FeignException
        ignoreExceptions:
          - java.lang.RuntimeException