server:
  port: 8083

spring:
  application:
    name: delivery-service

  datasource:
    url: jdbc:h2:mem:order_db
    driver-class-name: org.h2.Driver
    username: sa
    password: ""

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  kafka:
    bootstrap-servers: localhost:9093
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.type.mapping: message:com.iproddy.common.dto.kafka.OrderCreationStatusMessage
    listener:
      ack-mode: record
    consumer:
      group-id: delivery-service
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      auto-offset-reset: earliest
      enable-auto-commit: true
      properties:
        spring.json.use.type.headers: true
        spring.json.trusted.packages: com.iproddy.common.dto.kafka
        spring.json.type.mapping: message:com.iproddy.common.dto.kafka.OrderCreationStatusMessage

resilience4j:
  circuitbreaker:
    instances:
      deliveryControllerCircuitBreaker:
        registerHealthIndicator: true
        slidingWindowSize: 50
        failureRateThreshold: 50
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 10
        minimumNumberOfCalls: 20
        ignoreExceptions:
          - com.iproddy.common.exception.NotFoundException

kafka:
  topic:
    order-creation-status-topic: order.creation.status
    delivery-create-event-topic: delivery.create_event
